# Site settings
baseurl = "https://raetaylorburns.github.io/portfolio"
languageCode = "en-us"
sectionPagesMenu = "main"
theme = "frances"
publishDir = "docs"

[params]
	name = "Rae Taylor-Burns"
	description = "scientist + artist"
	author = "Rae Taylor-Burns"